<?php
/**
 * Zkilleman_Checkout
 *
 * Copyright (C) 2012 Henrik Hedelund (henke.hedelund@gmail.com)
 *
 * This file is part of Zkilleman_Checkout.
 *
 * Zkilleman_Checkout is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zkilleman_Checkout is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Zkilleman_Checkout. If not, see <http://www.gnu.org/licenses/>.
 *
 * @category  Zkilleman
 * @package   Zkilleman_Checkout
 * @author    Henrik Hedelund <henke.hedelund@gmail.com>
 * @copyright 2012 Henrik Hedelund (henke.hedelund@gmail.com)
 * @license   http://www.gnu.org/licenses/lgpl.html GNU LGPL
 * @link      https://github.com/henkelund/magento-zkilleman-checkout
 */
?>
<?php
    $_helper     = Mage::helper('zkilleman_checkout');
    $_containers = $_helper->containSteps($this->getSteps(), $this);
?>
<div class="page-title">
    <h1><?php echo $this->__('Checkout') ?></h1>
</div>
<script type="text/javascript" src="<?php echo $this->getJsUrl('varien/accordion.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/zkilleman_checkout.js') ?>"></script>
<div class="opc" id="checkoutSteps">
<?php foreach ($_containers as $container => $steps): ?>
    <ul class="step-container container-<?php echo $container; ?>">
    <?php foreach ($steps as $_stepId => $_stepInfo): ?>
        <li id="opc-<?php echo $_stepId ?>" class="section<?php echo !empty($_stepInfo['allow'])?' allow':'' ?><?php echo !empty($_stepInfo['complete'])?' saved':'' ?>">
            <div class="step-title">
                <span class="number"><?php echo $_stepInfo['counter'] ?></span>
                <h2><?php echo $_stepInfo['label'] ?></h2>
                <a href="#"><?php echo $this->__('Edit') ?></a>
            </div>
            <div id="checkout-step-<?php echo $_stepId ?>" class="step a-item">
                <?php echo $this->getChildHtml($_stepId) ?>
            </div>
        </li>
    <?php endforeach; ?>
    </ul>
<?php endforeach; ?>
</div>
<script type="text/javascript">
//<![CDATA[

    function checkoutStepToggle(step, open) {
        var effect = open ? Effect.BlindDown : Effect.BlindUp;
        var effectOptions = {duration: 0.2};
        if (step == 'opc-login') {
            var contents = Element.select(step, '.a-item');
            effect(contents[0], effectOptions);
        } else if (step == 'opc-shipping') {
            if (open || $('shipping:same_as_billing').checked) {
                effect('opc-shipping', effectOptions);
            }
        }
    }

    Element.hide('opc-shipping');

    var accordion = new Zkilleman_Accordion(
                            'checkoutSteps', '.step-title', true, {
                                onToggle: checkoutStepToggle
                            });
    <?php if($this->getActiveStep()): ?>
    accordion.openSection('opc-<?php echo $this->getActiveStep() ?>');
    <?php endif ?>
    var checkout = new Checkout(accordion,{
        progress: '<?php echo $this->getUrl('checkout/onepage/progress') ?>',
        review: '<?php echo $this->getUrl('checkout/onepage/review') ?>',
        saveMethod: '<?php echo $this->getUrl('checkout/onepage/saveMethod') ?>',
        failure: '<?php echo $this->getUrl('checkout/cart') ?>'}
    );
//]]>
</script>
