<?php
/**
 * Zkilleman_Checkout
 *
 * Copyright (C) 2012 Henrik Hedelund (henke.hedelund@gmail.com)
 *
 * This file is part of Zkilleman_Checkout.
 *
 * Zkilleman_Checkout is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zkilleman_Checkout is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Zkilleman_Checkout. If not, see <http://www.gnu.org/licenses/>.
 *
 * @category  Zkilleman
 * @package   Zkilleman_Checkout
 * @author    Henrik Hedelund <henke.hedelund@gmail.com>
 * @copyright 2012 Henrik Hedelund (henke.hedelund@gmail.com)
 * @license   http://www.gnu.org/licenses/lgpl.html GNU LGPL
 * @link      https://github.com/henkelund/magento-zkilleman-checkout
 */
?>
<?php
    $_helper         = Mage::helper('zkilleman_checkout');
    /* @var Zkilleman_Checkout_Helper_Data */
    $_containers     = $_helper->containSteps($this->getSteps(), $this);
    $_containersHtml = array();
?>
<div class="page-title">
    <h1><?php echo $this->__('Checkout') ?></h1>
</div>
<script type="text/javascript" src="<?php echo $this->getJsUrl('varien/accordion.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/zkilleman_checkout.js') ?>"></script>
<?php foreach ($_containers as $container => $steps): if (!empty($steps)): ob_start(); ?>
<ul class="step-container container-<?php echo $container; ?>">
    <?php foreach ($steps as $_stepId => $_stepInfo): ?>
    <li id="opc-<?php echo $_stepId ?>" class="section<?php echo !empty($_stepInfo['allow'])?' allow':'' ?><?php echo !empty($_stepInfo['complete'])?' saved':'' ?>">
        <div class="step-title">
            <span class="number"><?php echo $_stepInfo['counter'] ?></span>
            <h2><?php echo $_stepInfo['label'] ?></h2>
            <a href="#"><?php echo $this->__('Edit') ?></a>
        </div>
        <div id="checkout-step-<?php echo $_stepId ?>" class="step a-item">
            <?php echo $this->getChildHtml($_stepId) ?>
            <div class="overlay"></div>
        </div>
        <script type="text/javascript">
        //<![CDATA[
            Zkilleman_Checkout.resizeStepOverlay('opc-<?php echo $_stepId; ?>');
        //]]>
        </script>
    </li>
    <?php endforeach; ?>
</ul>
<?php $_containersHtml[$container] = ob_get_clean(); endif; endforeach; ?>
<div class="opc" id="checkoutSteps">
    <?php /* Render top, left, middle & right containers if they're not empty */ ?>
    <?php /* Copy this template to your theme if you need to wrap the steps in additional html */ ?>
    <?php if (isset($_containersHtml['top']))    { echo $_containersHtml['top'];    unset($_containersHtml['top']);    } ?>
    <?php if (isset($_containersHtml['left']))   { echo $_containersHtml['left'];   unset($_containersHtml['left']);   } ?>
    <?php if (isset($_containersHtml['middle'])) { echo $_containersHtml['middle']; unset($_containersHtml['middle']); } ?>
    <?php if (isset($_containersHtml['right']))  { echo $_containersHtml['right'];  unset($_containersHtml['right']);  } ?>
    <?php /* Flush the html array in case there are additional containers */ ?>
    <?php foreach (array_keys($_containersHtml) as $container): ?>
        <?php echo $_containersHtml[$container]; ?>
    <?php unset($_containersHtml[$container]); endforeach; ?>
</div>
<?php 
    $localOptions = array();
    if ($this->getActiveStep()) {
        $localOptions['active_step'] = $this->getActiveStep();
    }
    $optionsJson = $_helper->getCheckoutOptionsJson($localOptions);
?>
<script type="text/javascript">
//<![CDATA[

    var accordion = new Zkilleman_Accordion('checkoutSteps', '.step-title', true);
    var checkout  = new Zkilleman_Checkout(accordion, {
        review:     '<?php echo $this->getUrl('checkout/onepage/review') ?>',
        saveMethod: '<?php echo $this->getUrl('checkout/onepage/saveMethod') ?>',
        failure:    '<?php echo $this->getUrl('checkout/cart') ?>'}
    );
    checkout.setup(<?php echo $optionsJson; ?>);

//]]>
</script>
