<?php
/**
 * Zkilleman_Checkout
 *
 * Copyright (C) 2012 Henrik Hedelund (henke.hedelund@gmail.com)
 *
 * This file is part of Zkilleman_Checkout.
 *
 * Zkilleman_Checkout is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zkilleman_Checkout is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Zkilleman_Checkout. If not, see <http://www.gnu.org/licenses/>.
 *
 * @category  Zkilleman
 * @package   Zkilleman_Checkout
 * @author    Henrik Hedelund <henke.hedelund@gmail.com>
 * @copyright 2012 Henrik Hedelund (henke.hedelund@gmail.com)
 * @license   http://www.gnu.org/licenses/lgpl.html GNU LGPL
 * @link      https://github.com/henkelund/magento-zkilleman-checkout
 */
?>
<?php
    $_helper         = Mage::helper('zkilleman_checkout');
    $_containers     = $_helper->containSteps($this->getSteps(), $this);
    $_containersHtml = array();
?>
<div class="page-title">
    <h1><?php echo $this->__('Checkout') ?></h1>
</div>
<script type="text/javascript" src="<?php echo $this->getJsUrl('varien/accordion.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/zkilleman_checkout.js') ?>"></script>
<script type="text/javascript">
//<![CDATA[

    function resizeStepOverlay(step)
    {
        if (!$(step)) { return; }
        
        var height = 0;
        if (!Element.hasClassName(step, 'active')) {
            var content = Element.select(step, '.a-item');
            height = Element.getHeight(content[0]);
        }
        var overlay = Element.select(step, '.a-item .overlay');
        Element.setStyle(overlay[0], {'height': height + 'px'});
    }

//]]>
</script>
<?php foreach ($_containers as $container => $steps): if (!empty($steps)): ob_start(); ?>
<ul class="step-container container-<?php echo $container; ?>">
    <?php foreach ($steps as $_stepId => $_stepInfo): ?>
    <li id="opc-<?php echo $_stepId ?>" class="section<?php echo !empty($_stepInfo['allow'])?' allow':'' ?><?php echo !empty($_stepInfo['complete'])?' saved':'' ?>">
        <div class="step-title">
            <span class="number"><?php echo $_stepInfo['counter'] ?></span>
            <h2><?php echo $_stepInfo['label'] ?></h2>
            <a href="#"><?php echo $this->__('Edit') ?></a>
        </div>
        <div id="checkout-step-<?php echo $_stepId ?>" class="step a-item">
            <?php echo $this->getChildHtml($_stepId) ?>
            <div class="overlay"></div>
        </div>
        <script type="text/javascript">
        //<![CDATA[
            resizeStepOverlay('opc-<?php echo $_stepId; ?>');
        //]]>
        </script>
    </li>
    <?php endforeach; ?>
</ul>
<?php $_containersHtml[$container] = ob_get_clean(); endif; endforeach; ?>
<div class="opc" id="checkoutSteps">
    <?php /* Render top, left, middle & right containers if they're not empty */ ?>
    <?php /* Copy this template to your theme if you need to wrap the steps in additional html */ ?>
    <?php if (isset($_containersHtml['top']))    { echo $_containersHtml['top'];    unset($_containersHtml['top']);    } ?>
    <?php if (isset($_containersHtml['left']))   { echo $_containersHtml['left'];   unset($_containersHtml['left']);   } ?>
    <?php if (isset($_containersHtml['middle'])) { echo $_containersHtml['middle']; unset($_containersHtml['middle']); } ?>
    <?php if (isset($_containersHtml['right']))  { echo $_containersHtml['right'];  unset($_containersHtml['right']);  } ?>
    <?php /* Flush the html array in case there are additional containers */ ?>
    <?php foreach (array_keys($_containersHtml) as $container): ?>
        <?php echo $_containersHtml[$container]; ?>
    <?php unset($_containersHtml[$container]); endforeach; ?>
</div>
<script type="text/javascript">
//<![CDATA[

    function checkoutStepToggle(step, open)
    {
        if (!$(step)) { return; }
        
        var action = open ? Element.show : Element.hide;
        switch (step) {
            case 'opc-login':
                Element.select(step, '.a-item').each(function(el) {
                    action(el);
                });
                break;
            case 'opc-billing':
                var useForShipping = $('billing:use_for_shipping_yes');
                useForShipping = useForShipping ? useForShipping.checked : false;
                if (!open && useForShipping && (shippingStep = $('opc-shipping'))) {
                    action(shippingStep);
                }
                break;
            case 'opc-shipping':
                var sameAsBilling = $('shipping:same_as_billing');
                sameAsBilling = sameAsBilling ? sameAsBilling.checked : false;
                if (open || sameAsBilling) {
                    action(step);
                }
                if (useForShippingYes = $('billing:use_for_shipping_yes')) {
                    useForShippingYes.checked = sameAsBilling;
                }
                if (useForShippingNo = $('billing:use_for_shipping_no')) {
                    useForShippingNo.checked = !sameAsBilling;
                }
                break;
        }

        resizeStepOverlay(step);
    }

    if (shippingStep = $('opc-shipping')) {
        Element.hide(shippingStep);
    }

    var accordion = new Zkilleman_Accordion(
                            'checkoutSteps', '.step-title', true, {
                                onToggle: checkoutStepToggle
                            });
    <?php if($this->getActiveStep()): ?>
    accordion.openSection('opc-<?php echo $this->getActiveStep() ?>');
    resizeStepOverlay('opc-<?php echo $this->getActiveStep() ?>');
    <?php endif ?>
    var checkout = new Checkout(accordion, {
        review:     '<?php echo $this->getUrl('checkout/onepage/review') ?>',
        saveMethod: '<?php echo $this->getUrl('checkout/onepage/saveMethod') ?>',
        failure:    '<?php echo $this->getUrl('checkout/cart') ?>'}
    );
//]]>
</script>
